# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
    build:
        docker:
            # Use the same Docker base as the project
            - image: python:3.7.3-stretch

        working_directory: ~/repo

        steps:
            - checkout


            # Download and cache dependencies
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "requirements.txt" }}
                # fallback to using the latest cache if no exact match is found
                - v1-dependencies-

            - run:
                name: install dependencies
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    make install
                    # Install hadolint
                    wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                    chmod +x /bin/hadolint

            - save_cache:
                paths:
                - ./venv
                key: v1-dependencies-{{ checksum "requirements.txt" }}

            # run lint!
            - run:
                name: run lint
                command: |
                    . venv/bin/activate
                    make lint
                    make hadolint

            # new remote environment is created
            - setup_remote_docker:
                docker_layer_caching: true

            # install docker cli todo?
            - run:
                  name: Install Docker client
                  command: apt add docker-cli

            # build docker image
            - run:
                name: build
                command: |
                    export image_name_full=bitelds/fancy_app_image
                    docker build --no-cache --rm -t ${image_name_full}:${CIRCLE_BUILD_NUM} -t ${image_name_full}:latest .

            # login and push to DockerHub
            - run:
                  name: push
                  command:
                      export image_name_full=bitelds/fancy_app_image
                      echo $DOCKER_PASS | docker login -u bitelds --password-stdin
                      docker push ${image_name_full}:${CIRCLE_BUILD_NUM}
                      docker push ${image_name_full}:latest

            # run test
            - run:
                  name: run test
                  command: |
                      export PORT=8085
                      export image_name_full=bitelds/fancy_app_image
                      docker run -d --rm -p ${PORT}:${PORT} --name my_container ${image_name_full}:${CIRCLE_BUILD_NUM}
                      docker exec my_container curl --retry 10 --retry-connrefused http://localhost:${PORT}
